### PR TITLE
add ounce force (ozf) and rack units (U)

### PR DESCRIPTION
**Pull request by ioio85**
new imperial units

### CODE REVIEW

**Comment by hanna-kn** [comment]
I would prefer not reserving (by using "r" property) "U" for rack units. It might be a better choice to set RU or RackUnit (if RU is uncommon) as only reference name instead. In addition, using 'r' for two names is not really meaningful. Placing "RU" before "U" (in preference order) would also make it easier to change the usage of "U" later on, but this might possibly affect usability negatively.

**Comment by idamir** [comment]
A bit of humor: there’s a Russian unit of measure called the “vershok” which is equal to 1.75 inches.

Actually, `U' is quite common abbreviation for the `Rack Unit' as well as RU and RMU (Rack Mount Unit) and is refined in EIA-310-E standard.

**Comment by hanna-kn** [comment]
The reason that I'm hesitant about reserving 'U' for rack unit is that the unit is only relevant in a narrow context.

I will merge this pull request as it is and afterwards move the 'r' property to RackUnit. This change will not affect the end user.

**Comment by ioio85** [comment]
Thanks for merging, sorry I was away for a long time, It is ok if you don't want the U unit. I think RU is fine

**Pull request merged**
