### PR TITLE
Change defualt log base from e to 10

### PR DESCRIPTION
**Pull request by mymindstorm**
log(x) should use the common log by default as ln(x) is explicitly opting to use the natural log.

### CODE REVIEW

**Comment by hanna-kn** [comment]
log(x) is ambiguous and the interpretation is generally context dependent. The interpretation differs between different mathematical software. Both WolframAlpha and Matlab returns the natural logarithm, while many simple calculators return the common logarithm (although in this case the behaviour is usually made obvious by the fact that both ln and log buttons are present next to each other).

In Qalculate log() is primarily intended for logarithms with bases other than 10 or e, but for compatibility reasons the natural logarithm is returned if only one argument is specified. Changing this behaviour would break compatibility with earlier versions of Qalculate and create potential issues for users used to the current behaviour. I'm therefore hesitant about merging this pull request.

**Comment by mymindstorm** [comment]
Since Qalculate presents itself as a calculator rather than a scientific computation platform, I would expect Qalculate to follow the convention that scientific/graphing calculators set. 

How do you feel about requiring the base argument for `log()` instead? I understand that it isn't the best to break compatibility, but given that users (like me) may assume the incorrect base, I would think that it would be helpful to force the user to choose for log base-n rather than assume.

**Comment by hanna-kn** [comment]
I think the best would be to simply ask the user for the correct interpretation when log() is first used with a single argument.

**Comment by mymindstorm** [comment]
Closing this as fa51c5e6ed4f1145759e78eefefbedfdc1cfb1fd resolves the issue. Thank you!

**Pull request closed without merging**
