### PR TITLE
Add Clip function

### PR DESCRIPTION
**Pull request by arrufat**
Hello, I just want to get started by adding a simple function to Qalculate!

Please let me know if there's anything else I need to do.

Thank you :)

### CODE REVIEW

**Comment by hanna-kn** [comment]
Excellent.

The function seems to be properly written. There are alternate ways to implement this function, e.g. `if([\x<\Y{-infinity},\x>\Z{infinity}],[\y,\z],\x)` and/or with free type for arguments (with handle_vector explicitly set true), but I do not know if one alternative could be considered better than the other.

The names and description element names should however be prefixed with underscore (`_names`, `_description`), to mark them for translation. You can either fix this yourself or I can do it after merging.

**Comment by arrufat** [comment]
I will fix it myself, I want to have a complete PR I can use for reference.

Actually, the way I've written it already handles vectors, maybe because the `min` and `max` functions already do, but I can set the input value to be a free value instead. What do you think?

**Comment by hanna-kn** [comment]
> Actually, the way I've written it already handles vectors, maybe because the min and max functions already do, but I can set the input value to be a free value instead.

For number arguments the handle_vector property is true by default (meaning that the function is calculated separately for each value in the vector, otherwise the current function would fail). The only difference between using number and free types is, in this case, how they are presented to the user.

**Comment by arrufat** [comment]
Ah, I see, thank you for the explanation. What is the purpose of the `test` attribute? Or better, where can I find the information about this myself, so I don't have to bother you :)

**Comment by arrufat** [comment]
I also don't have a preference regarding the implementation (using `min` `max` or `if`) whichever is faster.

**Comment by hanna-kn** [comment]
> What is the purpose of the test attribute?

If the test attribute is false (default is true) no tests will be performed to check if the argument fulfils any specified conditions (in this case a number without an imaginary part). This also means that the argument value will not be evaluated (simplified) before it is inserted into the function expression. For "free" arguments (without any other specified conditions) the test attribute has no effect. If test was not set to false for the arguments in the clip function, the function would fail for non-numerical values (e.g. quantities with units).

> Or better, where can I find the information about this myself, so I don't have to bother you :)

The test attribute is unfortunately not documented.

> I also don't have a preference regarding the implementation (using min max or if) whichever is faster.

Min/max is 20-25% faster.

**Comment by arrufat** [comment]
Thank you again for the explanation.
I would have guessed that the `if` version would be faster, since it's done with a single call. I was wrong, I will revert the change, then.  How did you measure the time?
Regarding the test property, I will set it to true, since `min` and `max` won't work with complex numbers.

**Comment by arrufat** [comment]
Qalculate! is amazing.  I still can't believe that it exists.

**Comment by arrufat** [comment]
(By the way, there's a lot of noise in these commits... Instead of merging directly, maybe we should Squash all the commits)

**Comment by hanna-kn** [comment]
> I would have guessed that the if version would be faster, since it's done with a single call.

It is probably slower because the comparison is done using an expression instead of directly in the program code.

> How did you measure the time?

`time qalc "plot(clip(x,2,5),1,10,10000)"`

> With tests enabled, it might be slower than the other implementation.

The test property does not have any discernible impact on the speed.

**Comment by arrufat** [comment]
I am thinking of setting the values to “free” and handle_vector to true.
I have some other definitions for functions, and if I set them to numbers, the derivatives don't work as expected.

**Comment by arrufat** [comment]
I learned a lot, thank you :)

**Comment by hanna-kn** [comment]
I did some more testing and discovered that the function is five times faster without the condition (\y <= \z). (I should be able to make some general optimizations to improve this.)

> I am thinking of setting the values to “free” and handle_vector to true.

If unsure, it is generally a safe choice.

**Pull request merged**
